[package]
name = "{{ name }}"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
mu-sdk = "0.0.1"

[build-dependencies]
uuid = { version = "1.11.0", features = ["v4"] }
